apiVersion: v1
kind: Secret
metadata:
  name: push-secret
  annotations:
    build.knative.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: _json_key
  password: PUT_KEY_HERE